### ISSUE TITLE
Any way to receive notifications when the key's are removed because of TTL 

### ISSUE THREAD

**Issue by silviucpp** [fogfish/cache#13]
Hello,

Will be nice if you can provide in a way or other notifications when the key's are removed because of the TTL expired. 

Or in case you don’t want to implement this can you please let me know what part of the code is doing the delete of the expired key's.

Silviu

**Comment by fogfish** [comment]
Hello,

Cache makes eviction of segment (there are no eviction on key-level). You can be notified when segment is removed using `heir` property:
{heir,   atom() | pid()} - heir of evicted cache segments

```
cache:start_link(my_cache, [{n, 10}, {ttl, 60}, {heir, self()}]).
```

heir property triggers `ets:give_away(...)` feature, you process will get {'ETS-TRANSFER',Tab,FromPid,GiftData} message. You can use ETS table reference to handle eviction according to your  business logic.
https://github.com/fogfish/cache/blob/master/src/cache_heap.erl#L138
http://erldocs.com/current/stdlib/ets.html?i=0&search=ets:gi#give_away/3

Should it resolve your use-case?

**Comment by silviucpp** [comment]
Hello,

Thanks a lot. You can add this info in the documentation :) might be useful for others too. 

Silviu
