### ISSUE TITLE
start cache on distribute nodes makes crash

### ISSUE THREAD

**Issue by jianjyan** [fogfish/cache#14]
Hi,

my node down, due to cache started on distrubute nodes, and logs are attached, please have a look!

(xchat@192.168.0.100)1> 05:12:08.352 [warning] lager_error_logger_h dropped 63 messages in the last second that exceeded the limit of 50 messages/sec
05:12:08.352 [info] global: Name conflict terminating {pswd_cache,<29575.6921.0>}
05:12:08.352 [info] global: Name conflict terminating {sms_cache,<29575.6922.0>}
05:12:08.352 [info] global: Name conflict terminating {user_token_cache,<29575.6923.0>}
05:15:01.117 [error] Received a MNESIA down event, removing on node 'xchat@192.168.0.100' all pids of node 'xchat_dev@192.168.0.100'
05:23:17.800 [error] Received a MNESIA down event, removing on node 'xchat@192.168.0.100' all pids of node 'xchat_dev@192.168.0.100'
05:39:32.342 [info] global: Name conflict terminating {pswd_cache,<29575.4243.0>}
05:39:32.342 [info] global: Name conflict terminating {sms_cache,<29575.4244.0>}
05:39:32.342 [info] global: Name conflict terminating {user_token_cache,<29575.4245.0>}
05:39:35.178 [error] Received a MNESIA down event, removing on node 'xchat@192.168.0.100' all pids of node 'xchat_dev@192.168.0.100'
05:48:52.009 [info] global: Name conflict terminating {pswd_cache,<29575.7284.0>}
05:48:52.009 [info] global: Name conflict terminating {sms_cache,<29575.7285.0>}
05:48:52.009 [info] global: Name conflict terminating {user_token_cache,<29575.7286.0>}
05:49:02.789 [error] Received a MNESIA down event, removing on node 'xchat@192.168.0.100' all pids of node 'xchat_dev@192.168.0.100'
05:49:57.855 [info] global: Name conflict terminating {pswd_cache,<29575.818.0>}
05:49:57.859 [info] global: Name conflict terminating {sms_cache,<29575.819.0>}
05:49:57.860 [info] global: Name conflict terminating {user_token_cache,<29575.820.0>}

**Comment by fogfish** [comment]
Hello,
Thanks you the issue report.

The following error message give an indication that you environment has instance of global process with same name. You might see details about global processes here: http://erlang.org/doc/man/global.html
```
05:12:08.352 [info] global: Name conflict terminating {pswd_cache,<29575.6921.0>}
```

Basically, you can have only one instance of global cache within the cluster.

**Comment by fogfish** [comment]
Do you have any update on the issue? If not, I claim that global process registry cause crash .

**Comment by jianjyan** [comment]
Hi, I wrote code : 
case cache:start_link({global, pswd_cache}, [{policy, lru}, {n, 10}, {ttl, 3600}]) of
		{ok, _} -> ok;
		{error, {already_started, _}} -> ok;
		_ -> ok
	end,
in auth_process.erl, when I join a node to another, the crash occurs.
I did not register the pswd_cache manually, seems it's been registered some where in cache mode.
you know, I don't want to start the cache manually, therefore different nodes has the same code, it's better to avoid the problem in cache.

**Comment by fogfish** [comment]
I see what you mean. Let me investigate this further. 

My original though about `global` cache... It shall be executed within dedicated node -- a node that runs only cache application. Otherwise restart of your application terminates all data. Then, I've never had an intension to make it distributed fail-safe. You'll better use mnesia. 

So, I can protect the cache to resolve global conflict but how to resolve restart ?

**Comment by jianjyan** [comment]
I got your point. then I should use mnesia instead. thank you for your response.
