### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by a29107a** [fogfish/cache#15]
hello,
can you provide transaction in this lib?

when i use this lib, i maybe use like this:
       Value = cache:get({global, test}, key),
       NewValue = ....,
       cache:put({global, test}, key, NewValue),

if no transaction ,the cache maybe modify by other progress.

**Comment by fogfish** [comment]
Sounds a good proposal. I would make an `apply` function that take key and function to apply over the value.

**Comment by fogfish** [comment]
done

**Comment by a29107a** [comment]
thanks!
