### ISSUE TITLE
Sharding support

### ISSUE THREAD

**Issue by yzh44yzh** [fogfish/cache#18]
Nice work. I've spent some time exploring caching libraries for Erlang. And this library is really good.

Did you consider to add sharding? Currently all read/write queries go through gen_server:call to single process. And this is not good for my case.

Sharding could be added as separate library on top of "cache", or it could be implemented inside "cache". What option do you think will be better?

I am ready to do it myself and send PR to you.

**Comment by fogfish** [comment]
Hello, thank you for the feedback! 

Yes, sharding is extremely important feature. I've been thinking about it. So far, I've not incorporate it to this library but I had a a few solutions in my hand. They helps to implement sharding quickly.  

I've been developing a consistent hashing and cluster membership library. It helps to introduce reliable sharding. 
https://github.com/fogfish/datum/blob/master/src/sets/ring.erl
https://github.com/fogfish/ek

Let's look into first case when multiple shards are running on same node, then you just use `ring` module to load balance  traffic to multiple servers... a code might look like

```erlang
%% initiate consistent hash ring
Ring0 = ring:new([
   {m,      64}
,  {q,    4096}
,  {n,       1}
,  {hash,  sha}
]).

%% join cache shard to ring
{ok, _} = cache:start_link(<<"my_shard1">>, [{n, 10}, {ttl, 60}]).
Ring1 = ring:join(<<"my_shard1">>, Ring0).

{ok, _} = cache:start_link(<<"my_shard2">>, [{n, 10}, {ttl, 60}]).
Ring2 = ring:join(<<"my_shard1">>, Ring1).
...

%% use shards
{_, Shard} = hd(ring:successors(Key, Ring2)).
cache:put(Shard, Key, Value).
...
```

Unfortunately, I am missing an ability to use a binary names for cache object, `cache:start_link(<<"my_shard1">>, ...)` will fail, only atoms are supported. I need to merge `via` protocol support to cache library first: 
https://github.com/petrkozorezov/cache/commit/b02ca876c26397e1dc95e832617003aef5c5a029

after that it would be easy to support local shards.

A second example of cluster distributed shards (it requires more thoughts). The library `ek` has all necessary support.

```erlang
%% create distributed shard management
ek:pg(my_cluster).
ek:router(my_cache, my_cluster, [
   {m,      64}
,  {q,    4096}
,  {n,       1}
,  {hash,  sha}
]).

%% join cache shard to ring
{ok, Shard1} = cache:start_link([{n, 10}, {ttl, 60}]).
ek:join(my_cluster, <<"my_shard1">>, Shard1).

{ok, Shard2} = cache:start_link([{n, 10}, {ttl, 60}]).
ek:join(my_cluster, <<"my_shard2">>, Shard2).
...

%% use shards
Shard = hd(ek:successors(my_cache, Key)).
cache:put(ek:vnode(peer, Shard), Key, Value).
``` 

This is roughly any options how to implements a sharding. A few things needs to be considered here
* How to manage deps, I'd like to avoid a case where half of internet needs to be downloaded just to build and use `cache` library in simplest case
* Validate the performance of `ek:successors(my_cache, Key)` long time about I've been doing benchmarks the shard route resolution is was about 60K req/sec and if the perf is not good enough than some other solution is required.

but I would be nice to get your feedback about subject above.

**Comment by yzh44yzh** [comment]
Well, consistent hashing is cool, but simple `NumShards rem Hash` approach is also useful in many cases. (Keep it simple :).

And if we need shard names as atoms, do you think `list_to_atom("shard_" ++ "1")` will be awful?

**Comment by yzh44yzh** [comment]
I believe It's ok to have one or two transient deps. May be even 5 transient deps. And this is not the same as having half of the internet in deps :)

**Comment by fogfish** [comment]
Yes, `Hash rem NumShards` will definitely work. Just spawn shards behind supervisor. What is your proposal about `NumShards`. Where do keep it? It should be a fast enough because NumShards is needed by each IO.   
* ets
* user supervisor:which_children 
* something else

**Comment by yzh44yzh** [comment]
Application env is not a bad place to keep NumShards. 
```
-spec init(atom(), pos_integer(), pid()) -> ok | {error, already_exists}.
init(Name, NumShards, Sup) ->
    CacheShards = application:get_env(some_app, cache_shards, #{}),
    case maps:find(Name, CacheShards) of
        {ok, _} -> {error, already_exists};
        error ->
            CacheShards2 = CacheShards#{Name => NumShards},
            start_shards(Name, NumShards, Sup)
    end.
```

I have hardcoded app name here, but it could be send with arguments as well.

**Comment by yzh44yzh** [comment]
That's the idea https://pastebin.com/sgjjQr9t

It works for me. It could be added as a single module to your library.

One important thing here is that app env is formed dynamically instead of using sys.config. But we can set the full configuration in sys.config instead.

If you ok with the idea, I will make a proper code and tests and will send you a PR.

**Comment by fogfish** [comment]
Sounds excellent!

**Comment by yzh44yzh** [comment]
ok, I will do it

**Comment by yzh44yzh** [comment]
So, now we have working solution )

**Comment by fogfish** [comment]
hex package is published, `2.3.0`.
I've slightly adjusted initialisation api of shared cache to make it OTP compliment.

**Comment by yzh44yzh** [comment]
Thank you

**Comment by yzh44yzh** [comment]
@fogfish you may be interested to know that we have sharding cache in production for half a year on many machines and everything works fine.

**Comment by fogfish** [comment]
This is a really great news! Thank you for sharing it!
